
package com.itbuzzpress.chapter2.wsdemo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-10T21:55:06.253+02:00
 * Generated source version: 3.0.1
 * 
 */
public final class Customer_CustomerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wsdemo.chapter2.itbuzzpress.com/", "CustomerService");

    private Customer_CustomerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerService ss = new CustomerService(wsdlURL, SERVICE_NAME);
        Customer port = ss.getCustomerPort();  
        
        {
        System.out.println("Invoking locateCustomer...");
        java.lang.String _locateCustomer_firstName = "_locateCustomer_firstName1968445715";
        java.lang.String _locateCustomer_lastName = "_locateCustomer_lastName-533371064";
        com.itbuzzpress.chapter2.wsdemo.USAddress _locateCustomer_address = new com.itbuzzpress.chapter2.wsdemo.USAddress();
        _locateCustomer_address.setAddress("Address2004615010");
        com.itbuzzpress.chapter2.wsdemo.CustomerRecord _locateCustomer__return = port.locateCustomer(_locateCustomer_firstName, _locateCustomer_lastName, _locateCustomer_address);
        System.out.println("locateCustomer.result=" + _locateCustomer__return);


        }

        System.exit(0);
    }

}
