package com.itbuzzpress.chapter2.wsdemo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-10T21:55:06.333+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/", name = "Customer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Customer {

    @WebResult(name = "CustomerRecord", targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/", partName = "CustomerRecord")
    @WebMethod
    public CustomerRecord locateCustomer(
        @WebParam(partName = "FirstName", name = "FirstName")
        java.lang.String firstName,
        @WebParam(partName = "LastName", name = "LastName")
        java.lang.String lastName,
        @WebParam(partName = "Address", name = "Address")
        USAddress address
    );
}
