
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.itbuzzpress.chapter2.wsdemo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-10T21:55:06.313+02:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerService",
                      portName = "CustomerPort",
                      targetNamespace = "http://wsdemo.chapter2.itbuzzpress.com/",
                      wsdlLocation = "file:/D:/jaxws/ws-demo-wsdl-1.0/CustomerService.wsdl",
                      endpointInterface = "com.itbuzzpress.chapter2.wsdemo.Customer")
                      
public class CustomerPortImpl implements Customer {

    private static final Logger LOG = Logger.getLogger(CustomerPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.itbuzzpress.chapter2.wsdemo.Customer#locateCustomer(java.lang.String  firstName ,)java.lang.String  lastName ,)com.itbuzzpress.chapter2.wsdemo.USAddress  address )*
     */
    public com.itbuzzpress.chapter2.wsdemo.CustomerRecord locateCustomer(java.lang.String firstName,java.lang.String lastName,USAddress address) { 
        LOG.info("Executing operation locateCustomer");
        System.out.println(firstName);
        System.out.println(lastName);
        System.out.println(address);
        try {
            com.itbuzzpress.chapter2.wsdemo.CustomerRecord _return = new com.itbuzzpress.chapter2.wsdemo.CustomerRecord();
            _return.setFirstName("FirstName2077179262");
            _return.setLastName("LastName-7680089");
            com.itbuzzpress.chapter2.wsdemo.USAddress _returnAddress = new com.itbuzzpress.chapter2.wsdemo.USAddress();
            _returnAddress.setAddress("Address1019050865");
            _return.setAddress(_returnAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
